name: todoapp
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  path: ^1.8.3
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  json_serializable: ^6.7.1
  dio: ^5.3.3
  redux_saga: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

